### ISSUE TITLE
need your help old iron

### ISSUE THREAD

**Issue by huixiancheng** [CoinCheung/BiSeNet#115]
hi,sir cheung.Thanks for such good code.Here is the trouble i meet.
As i see,
https://github.com/CoinCheung/BiSeNet/blob/90de8f9bdb6281f700087a5384996b18a4c6dae7/lib/models/bisenetv1.py#L62-L69
you use nn.PixelShuffle to upsample the feature map.
**However,for some reasons ,I need only downsample the width and keep the height.so i only need upsample the width**
So it's look like i need to change this part.Since nn.PixelShuffle only transform (∗,C^r,H,W ) to  (∗,C,rH,rW )
so could i use **upsample** or **F.interpolate** or **torch.nn.ConvTranspose2d** to replace this part?
will this affect network performance?

**Comment by CoinCheung** [comment]
Hi,

I used `nn.PixelShuffle` because it can be parsed correctly by tensorrt 7.0.0 through onnx. From my observation, changing `nn.PixelShuffle` to `F.interpolate` will harm model miou, and will reduce the model parameters and accererate model inference. So I think you can change that into `F.interpolate` if you do not want to deploy with tensorrt 7.0.0. 

By the way, if you use `F.interpolate` and train your model with pytorch native fp16 mode, you might see training speed gets much slower. It is a bug in pytorch, and has been fixed but not included in pytorch1.7.0. There are two methods to handle this, one is  using apex for fp16 training, and another is installing pytorch nightly version. 

Just follow your intuition, good luck :)

**Comment by huixiancheng** [comment]
Thank you for such  quick reply ！:thumbsup: 
I will take a try :running:
