### ISSUE TITLE
 Get the confidence of the segmented class during test time

### ISSUE THREAD

**Issue by poornimajd** [CoinCheung/BiSeNet#126]
Hello, @CoinCheung 
I am trying to figure out if there is a way to get the network also give the confidence of the segmented class during test time.Basically give how accurate the network thinks the segmentation output is.
I figured out that in the evaluate.py script,the following line gives the probability of each pixel belonging to a particular class.
https://github.com/CoinCheung/BiSeNet/blob/master/tools/evaluate.py#L119
But the probability which is returned in the following function
https://github.com/CoinCheung/BiSeNet/blob/master/tools/evaluate.py#L146
is a scaled probability,having values greater then 1,even though I passed the scaling factor as 1 in this function.
I had the following questions-

  1.What is the difference between scaled probability and the probability returned by the first case.
   2.To find the confidence of the segmented class,I am just taking the mean of the probability of the pixels belonging to a particular class ,returned by the first case(i.e no scaling).Is this a correct way of finding the confidence of the segmented class during test time(i.e no ground truth is present).
   3.Since the scaled probability is greater than 1 for some pixels,how can we use this to find the confidence of the segmented region?

Any suggestion would be really helpful.
 Thankyou

**Comment by CoinCheung** [comment]
Hi, 

1. the probability is not scaled but accumulated. The purpose of interpolation operation is to rescale the spatial size of input and output tensor not its probability values. You observe some of the probability value is greater than 1 because it is the summation result of  multi-scale inference.

2. You can sum up all pixels' probability scores of each class to determine the confidence. You can also use iou of each as a criteria. That depends on your application, you can have try to verify them.

3. If you want to have probability scores within range [0, 1], Before the following line: 

 https://github.com/CoinCheung/BiSeNet/blob/90de8f9bdb6281f700087a5384996b18a4c6dae7/tools/evaluate.py#L170

you can simply add this:
```
scores = probs.softmax(dim=1)
```
This should work.

**Comment by poornimajd** [comment]
Thank you for the reply.I will check this out.

**Comment by CoinCheung** [comment]
You might have solved your problem, so I am closing this.
