### ISSUE TITLE
Reported Bisenet2 results worse than Bisenet1

### ISSUE THREAD

**Issue by russelldj** [CoinCheung/BiSeNet#203]
In your `README` you report that for every metric version 1 performs better than version 2. Is this correct? Is there something else that's better about version 2 that is not captured in that table?

**Comment by CoinCheung** [comment]
I remember I mentioned this somewhere in other issues. Bisenetv2 has lower times of compution, due to the usage of seperate convolution and smaller channel number. This brings the merit of light-weighted model, but also brings two side effect. One is low-efficiency of memory access, because currently(until 2021.12), most gpus use DRAM as their global memory, which is  preferred to be accessed contineously. Seperate convolution does not access global memory one cell after another, thus the bandwidth cannot be fully utilized. This is the reason why bisenetv2 has lower flops but is not faster than bisenetv1. Another side effect is smaller model capacity. People believe low model capacity leads to under-fitting, thus the metric of miou is lower.
