### ISSUE TITLE
Model is not saved in training

### ISSUE THREAD

**Issue by JINGTING92** [CoinCheung/BiSeNet#27]
Hi, there, I am a newbie at pytorch. I did not find any codes about saving the models during training, only the final model is saved after 80k iterations, is that correct? What if the training process is interrupted by accident? Where can I find the log or restore the trained parameters?? 

By the way, I am using 2 Tesla K80 to train the model, and it takes almost 2 days for the first 33950 iters. However, the author claims that it takes almost 1 day using 2 1080ti. What am I missing?

**Comment by CoinCheung** [comment]
1. yes you are correct on this. I did not write any code the checkpoint dumping and restoring since I can finish training within one day and our server is stable enough to stay training without too much breaks.

2. I am not sure about the difference on flops between 108ti and tesla k80. Maybe this is some problem brought by the gpu or the environment. 

Also it can be brought by inplace-abn, if you are using other version pytorch. If your gpus have enough memory, you can try to replace the inplace-abn with the official sync-bn and see if things are better.
